name: coverage

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env: 
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v18

    - uses: cachix/cachix-action@v16
      with:
        name: tmayoff
        authToken: '${{ secrets.CACHIX_AUTH }}'

    - name: Coverage
      run: |
        nix develop --command cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
