name: coverage


on:
  push:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - name: Coverage
      run: |
        nix develop --command cargo tarpaulin -o stdout >> $GITHUB_STEP_SUMMARY
