name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5      
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: taiki-e/install-action@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          tool: wasm-pack

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: wasm-pack build --target web --scope tmayoff

      - uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd pkg
          npm publish

