name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: taiki-e/install-action@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          tool: wasm-pack

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: wasm-pack build

      - run: |
          cd pkg
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
