name: build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: DeterminateSystems/flake-checker-action@v12
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack

      - name: Build
        run: wasm-pack build --target web
      
