name: Update Nix

on:
  schedule: 
    - cron: "0 0 * * 6"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v15
    - uses: DeterminateSystems/update-flake-lock@v24
      with: 
        token: ${{ secrets.FLAKE_PR_TOKEN }}
